name: .NET

on:
  push:
    branches: [ master, feature, data-layer ]
  pull_request:
    branches: [ master, feature, data-layer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[*CustomerLibrary.Data]*" /p:ExcludeB="[*IntegrationTests]*" /p:CoverletOutput=TestResults/
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./CustomerLibraryTests/TestResults/coverage.opencover.xml
        flags: unittests 
        name: codecov-umbrella
        fail_ci_if_error: true 
        verbose: true
