name: Test Calculator
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Generate test coverage report
        run: dotnet test --collect:"XPlat Code Coverage"
      
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ./CustomerLibraryTests/TestResults/**/coverage.cobertura.xml

      
